- name: Test ec2 info
  hosts: localhost
  #connection: local

  tasks:
    - name: Get EC2 Info
      ec2_instance_info:
        filters:
          "tag:Name": "ansible"
      register: ec2_name

    - name: Get instance IP addresses.
      debug:
          msg: "ec2_name"