- name: Ansible Play
  hosts: localhost
  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        region: us-east-1
        count: 2
        # key_name: "prod-ssh-key"
        vpc_subnet_id: subnet-08bbb2c0becc01597
        instance_type: t2.micro
        security_group: sg-00c14e6d6ba354df2
        network:
          assign_public_ip: true
        image_id: ami-03265a0778a880afb
        tags:
          Environment: Testing